#define IDS_APP_TITLE                   101
#define IDS_GAME_WINDOW_NAME            102
#define IDI_APP_ICON                    103
#define IDR_APP_MENU                    104
#define IDS_APP_WINDOW_CLASSNAME        105
#define IDM_ICON                        40000
#define IDM_FINGERPRINTSCANNER          40001
#define IDM_KEYPADCRACKER               40002
#define IDM_EXIT                        40003
